[build]
  publish = "public"

# توجيه كل طلبات HLS عبر Cloudflare Worker
[[redirects]]
  from = "/hls/*"
  to = "https://races-player.it-f2c.workers.dev/hls/:splat"
  status = 200
  force = true

# SPA fallback (لو احتجته لاحقًا)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
