[build]
  publish = "public"

# احتياطي فقط لو أحد طلب /hls/* من نتلايفي؛ نعيد توجيه المتصفح إلى الوركر
[[redirects]]
  from = "/hls/*"
  to = "https://races-player.it-f2c.workers.dev/hls/:splat"
  status = 302
  force = true
  headers = { Cache-Control = "no-store" }
