name = "races-player"
main = "src/index.js"
compatibility_date = "2025-09-01"

[vars]
# استخدم http مع الـ IP لتفادي TLS مع عنوان IP. إن كان عندك دومين بشهادة صحيحة غيّرها إلى https://your-origin.example.com
ORIGIN_BASE = "http://46.152.17.35"

# مهلة طلبات المنبع (ms)
PROXY_TIMEOUT_MS = "15000"

# مدة كاش للشرائح (ثواني)
CACHE_SEGMENT_SECONDS = "25"
