name = "races-player"
main = "src/index.js"
compatibility_date = "2025-09-01"

[vars]
# ضع هنا الدومين/الآيبي الذي يقدم الـ HLS عندك (بدون /hls في المسار)
# استخدم http لو كان المصدر آيبي لتفادي مشكلة TLS مع الشهادات على الـ IP
ORIGIN_BASE = "http://46.152.17.35"

# مهلة الطلبات للأصل (مللي ثانية)
PROXY_TIMEOUT_MS = "15000"

# (اختياري) كاش لشرائح TS/M4S لتخفيف الحمل والتقطيع
CACHE_SEGMENT_SECONDS = "25"

# (اختياري) إن كان الأصل يتطلب Host معيّن لكنك تضطر للاتصال على IP:
# اجعل ORIGIN_BASE = "http://example.com" وأضف:
# UPSTREAM_RESOLVE_IP = "46.152.17.35"
# سيُنشئ اتصالاً إلى الآيبي لكن بـ Host=example.com
# UPSTREAM_RESOLVE_IP = "46.152.17.35"
