name = "hls-proxy"
main = "src/index.js"
compatibility_date = "2025-09-27"
workers_dev = true

[vars]
# استخدم http لتفادي TLS مع IP؛ غيّرها https لو عندك دومين بشهادة صحيحة
ORIGIN_BASE = "https://answer-moreover-joe-fragrance.trycloudflare.com"
PROXY_TIMEOUT_MS = "15000"
