name = "races-player"
main = "src/index.js"
compatibility_date = "2025-09-01"

[vars]
# استخدم http مع الـ IP إن لم تكن لديك شهادة HTTPS على الدومين الأصلي
ORIGIN_BASE = "http://46.152.17.35"

# مهلة المنبع (ms)
PROXY_TIMEOUT_MS = "15000"

# مدة الكاش للشرائح (ثواني)
CACHE_SEGMENT_SECONDS = "25"
